version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8.x
  build:
    commands:
      - ant war
artifacts:
   files:
      - '**/*'
      - appspec.yml
      - application-start-hook.sh
   discard-paths: yes
